spring:
  application:
    name: torip
  lifecycle:
    timeout-per-shutdown-phase: 120

  datasource:
    url: ENC(pKVVajA7+LVU36jCm6g1Un8eZUBUMEOeHOETLogC7LOXcCUv95YkA2GOrV4iO8dTGCGz07D0ZUtaOeaM3IeDVofvJZh3NWWnSIbahGAEou/EwAWYpGP56MWJYTFmpucVJpgdn/gOLIA=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(LgLrkT0khBL+kgrGYDyGlp+ppmt8H0z9)
    password: ENC(lTsm0BH9YoDHtZlPvGsRV5cbDRzX1GA2)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

jwt:
  expiredAccessTokenMs: 600000
  expiredRefreshTokenMs: 86400000
  secretKey: ENC(N+AnyaBk0MGt58SHgUFDn6QLWvhUSU5MVpWMcigoNUDnDjwxqheFtpNBV9IO8EnG)

## Jasypt
jasypt:
  encryptor:
    key: ${jasypt_key}

server:
  shutdown: graceful

cloud:
  aws:
    credentials:
      access-key: ENC(QtldJ/h2U1UGb0Zfmf2RkggGD08nRsPcQxkSF2+xyhE=)
      secret-key: ENC(ZtjaK/1Tb791Ju8ay/v5NSMSH5fmupELDujmeestR+BGOSwRLhB0sVtfRMmRmknXwF/zrgmvP58=)
    region:
      static: ENC(x6/uuqcHpKqcLwYSWMfOZtRPHXBGSejO)
    s3:
      bucket: ENC(5RyziorhkYWj9Zxqxt3Ykg==)

kakao:
  client-id: ENC(lb+ijDoAn4pk8tE3t+Kj+JgwV4puWKFQZalN3QdmRUdcxEg18VObEy5IJQlj9FOJ)
  client-secret: ENC(UL6uVUZehMa5WBQgh6B3xPwF6c7FgBot2lMW7hf2RFfaZwO7o9iDOpuUMJEnt0Sx)