spring:
  application:
    name: torip
  lifecycle:
    timeout-per-shutdown-phase: 120

  datasource:
    url: ENC(pKVVajA7+LVU36jCm6g1Un8eZUBUMEOeHOETLogC7LOXcCUv95YkA2GOrV4iO8dTGCGz07D0ZUtaOeaM3IeDVofvJZh3NWWnSIbahGAEou/EwAWYpGP56MWJYTFmpucVJpgdn/gOLIA=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(LgLrkT0khBL+kgrGYDyGlp+ppmt8H0z9)
    password: ENC(lTsm0BH9YoDHtZlPvGsRV5cbDRzX1GA2)

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


jwt:
  expiredAccessTokenMs: 600000
  expiredRefreshTokenMs: 86400000
  secretKey: ENC(N+AnyaBk0MGt58SHgUFDn6QLWvhUSU5MVpWMcigoNUDnDjwxqheFtpNBV9IO8EnG)

## Jasypt
jasypt:
  encryptor:
    key: ${jasypt_key}

server:
  shutdown: graceful