name: Java Build and Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        env:
          MY_SECRET: ${{ secrets.JASYPT_KEY }}
        run: ./gradlew build -x test

      - name: Check if JAR file exists
        run: ls -l ./build/libs/

      - name: Copy jar file to remote
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          source: "./build/libs/torip-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user"

      - name: Deploy to dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            sudo pkill -f 'java -jar torip-0.0.1-SNAPSHOT.jar' || true
            sudo ./run_app.sh
